<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="234765" started-at="2015-02-26T20:57:48Z" finished-at="2015-02-26T21:01:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="234765" started-at="2015-02-26T20:57:48Z" finished-at="2015-02-26T21:01:42Z">
      <class name="com.example.tests.SignupTest">
        <test-method status="FAIL" signature="createMailUser()[pri:0, instance:com.example.tests.SignupTest@37574691]" name="createMailUser" is-config="true" duration-ms="0" started-at="2015-02-26T22:57:48Z" finished-at="2015-02-26T22:57:48Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.example.tests.SignupTest.createMailUser(SignupTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createMailUser -->
        <test-method status="SKIP" signature="newUserShouldSignup()[pri:0, instance:com.example.tests.SignupTest@37574691]" name="newUserShouldSignup" duration-ms="8" started-at="2015-02-26T23:01:42Z" finished-at="2015-02-26T23:01:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newUserShouldSignup -->
        <test-method status="SKIP" signature="deleteMailUser()[pri:0, instance:com.example.tests.SignupTest@37574691]" name="deleteMailUser" is-config="true" duration-ms="0" started-at="2015-02-26T23:01:42Z" finished-at="2015-02-26T23:01:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteMailUser -->
      </class> <!-- com.example.tests.SignupTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
